#!/bin/sh

# Update packages
sudo apt update

# Install tooling
install_node() {
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    nvm install --latest
}

install_asdf() {
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
}

install_python() {
    sudo apt install -y build-essential libssl-dev libreadline-dev libbz2-dev libsqlite3-dev zlib1g-dev libffi-dev liblzma-dev python3.10-distutils
    ~/.asdf/bin/asdf plugin-add python
    ~/.asdf/bin/asdf install python 3.10.9
    ~/.asdf/bin/asdf global python 3.10.9

    curl -sSL https://install.python-poetry.org | python3 -
}

install_node
install_asdf
install_python

# Install customizations
install_fish() {
    sudo apt-add-repository -y ppa:fish-shell/release-3
    sudo apt update
    sudo apt install -y fish

    fish -N -c "curl -sL https://git.io/fisher | source && fisher udpate"
}

install_starship() {
    curl -sS https://starship.rs/install.sh | sh
}

configure_vim() {
    vim +PlugInstall +qa
}

configure_yadm() {
    echo "Updating the yadm repo origin URL"
    yadm remote set-url origin "git@github.com:cttibbetts/dotfiles.git"
}


install_fish
install_starship
configure_vim
configure_yadm

